SELECT
    id AS license_id,
    name AS license_number,
    musw__applicant__c AS contact_id,
    musw__primary_licensee__c AS account_id,
    board__c AS board_name,
    board_action__c AS board_action,
    musw__status__c AS status,
    sub_status__c AS sub_status,
    sub_category__c AS sub_category,
    musw__type__c AS type,
    business_license__c AS business_license,
    hide_from_public__c AS hide_from_public,
    hide_from_portal__c AS hide_from_portal,
    compact_eligible__c AS compact_eligible_flag,
    musw__issue_date__c AS license_issue_date,
    effective_date__c AS license_effective_date,
    musw__expiration_date__c AS license_expiration_date,
    licensee_name__c as licensee_name,
    lastmodifieddate
FROM {{ source('ELICENSE_RAW', 'LICENSE') }}
